{% set version = "0.1-7.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mlecens
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MLEcens_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MLEcens/MLEcens_{{ version }}.tar.gz
  sha256: 6dcedc79881e89ced1484395a4f409bf10824187b425bdfc8ec6fe805e5cf7dc

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - libblas
    - liblapack
  run:
    - r-base
    - libblas
    - liblapack

test:
  commands:
    - $R -e "library('MLEcens')"           # [not win]
    - "\"%R%\" -e \"library('MLEcens')\""  # [win]

about:
  home: http://stat.ethz.ch/~maathuis/
  license: GPL-2.0-or-later
  summary: This package contains functions to compute the nonparametric maximum likelihood estimator (MLE) for the bivariate distribution of (X,Y), when realizations of (X,Y) cannot be observed directly.  To be more precise, we consider the situation where we observe a set of rectangles that are known to contain the unobservable
    realizations of (X,Y). We compute the MLE based on such a set of rectangles.  The methods can also be used for univariate censored data (see data set 'cosmesis'), and for censored data with competing risks (see data set 'menopause').  We also provide functions to visualize the observed data and the MLE.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
